name: Go CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod tidy

      - name: Run lint
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test ./... -v
