name: Go CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: macos-15

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4
          architecture: arm64

      - name: Install PJRT dependencies
        run: curl -sSf https://raw.githubusercontent.com/gomlx/gopjrt/main/cmd/install_darwin_arm64.sh | bash

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        env:
          CGO_ENABLED: 1
        run: go build -v ./...

      - name: Run tests
        env:
          CGO_ENABLED: 1
        run: go test ./...
      
      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: regression-plots
          path: ./linearregression/onefeature/plot
